[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "capstone"
version = "0.0.1"
description = "bootcamp"
authors = [
  { name = "Bay Mijid" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.13.5"


[tool.ruff]
line-length = 99
src = ["capstone"]
include = ["pyproject.toml", "capstone/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["capstone"]
force-sort-within-sections = true

